import { Link, useRouterState } from '@tanstack/react-router';
import { useEffect, useState, type ReactNode } from 'react';
import { ArrowRight, ArrowDown, ChevronLeft, ChevronRight, Menu as MenuIcon, X, Coffee, CalendarDays, Sun } from 'lucide-react';
import { Button } from '@/components/ui/button';
import data from '@/data/sevn.json';
import coffee from '@/assets/coffee-ritual.jpg';
import bakery from '@/assets/bakehaus.jpg';
import room from '@/assets/cafe-room.jpg';
import { useHeroPanels } from './use-hero-panels';
export { data, coffee, bakery, room };
export const decode = (s: string) => s.replaceAll('&amp;', '&');
export function pageHead(title: string, description: string) { return { meta: [{ title: `${title} — SEVN Café & Bakehaus` }, { name: 'description', content: description }, { property: 'og:title', content: `${title} — SEVN Café & Bakehaus` }, { property: 'og:description', content: description }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] }; }
export function Wordmark() { return <span className="logo"><span className="wordmark">S<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 5.6c6-.7 12-.7 18 0v2.1c-6-.6-12-.6-18 0zM4.4 11c5.1.7 10.1.7 15.2 0v2c-5.1-.6-10.1-.6-15.2 0zM3 16.3c6-.6 12-.6 18 0v2.1c-6-.7-12-.7-18 0z"/></svg>VN</span><span className="logo-sub">Café &amp;<br/>Bakehaus</span></span> }
export function SiteShell({ children }: { children: ReactNode }) {
 const path = useRouterState({select:s=>s.location.pathname}); const [scrolled,setScrolled]=useState(false);const [open,setOpen]=useState(false);
 useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>70);onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);
 useEffect(()=>{setOpen(false); if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return; const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.animate([{opacity:0,transform:'translateY(22px)'},{opacity:1,transform:'translateY(0)'}],{duration:800,easing:'cubic-bezier(.22,1,.36,1)'});observer.unobserve(entry.target)}})},{threshold:0.12});document.querySelectorAll('.feature,.section-title,.note-rows>div').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[path]);
 useEffect(()=>{if(!open)return; const old=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',key)}},[open]);
 const nav=<><Link to="/" activeOptions={{exact:true}} activeProps={{'aria-current':'page'}}>Home</Link><Link to="/menu" activeProps={{'aria-current':'page'}}>Menu</Link><Link to="/story" activeProps={{'aria-current':'page'}}>Our story</Link><Link to="/journal" activeProps={{'aria-current':'page'}}>Journal</Link><Link to="/visit" activeProps={{'aria-current':'page'}}>Visit</Link><Link to="/franchise" className="partner-nav" activeProps={{'aria-current':'page'}}>Partner with SEVN</Link></>;
 return <><header className={`site-header ${scrolled||open?'solid':''}`}><Link to="/" aria-label="SEVN Café & Bakehaus home"><Wordmark/></Link><nav className="header-links" aria-label="Main navigation">{nav}<div className="header-tools"><Button variant={scrolled?'cafe':'hero'} asChild><Link to="/book">Book a table <ArrowRight/></Link></Button></div></nav><Button variant="tool" className="mobile-open" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<MenuIcon/>}</Button></header>{open&&<nav className="mobile-sheet" aria-label="Mobile navigation">{nav}<Link to="/book">Book a table</Link></nav>}<main className="route-content" key={path}>{children}</main><footer className="site-footer"><div className="container"><div className="footer-grid"><div><Link to="/" aria-label="SEVN home"><Wordmark/></Link><p>Café &amp; Bakehaus.<br/>Rooted in craftsmanship, guided by simplicity.</p><p className="mt-4">What would you come back for?</p></div><div><h3>Find your moment</h3><ul><li><Link to="/menu">The menu</Link></li><li><Link to="/story">Our story</Link></li><li><Link to="/journal">From the journal</Link></li><li><Link to="/book">Book a table</Link></li><li><Link to="/franchise">Partner with SEVN</Link></li></ul></div><div><h3>Come by</h3><p>Ground floor, Linking Road<br/>Bandra West, Mumbai 400050</p><p className="mt-3">Mon–Thu · 07:00–22:00<br/>Fri · 07:00–23:00<br/>Sat · 08:00–23:00 · Sun · 08:00–22:00</p><a href="mailto:hello@sevn.cafe">hello@sevn.cafe</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} SEVN Café &amp; Bakehaus</span><a href="https://www.instagram.com/sevn.cafe/" target="_blank" rel="noreferrer">Instagram ↗</a><span>Elevating everyday moments.</span></div></div></footer></>
}
export function SectionTitle({label,title,children}:{label:string;title:string;children?:ReactNode}) {return <div className="section-title"><p className="eyebrow">{label}</p><h2>{title}</h2><div className="small-rule"/>{children}</div>}
export function PageCover({title,label,image=coffee}:{title:string;label:string;image?:string}){return <section className="cover page-cover"><img src={image} alt="" width="1600" height="1024"/><div className="cover-content"><p className="eyebrow">{label}</p><h1>{title}</h1><div className="small-rule"/></div></section>}
export function MenuRows({items}:{items:typeof data.menu[number]['items']}){return <>{items.map(item=><div className="menu-row" key={item.n}><div className="menu-top"><h3>{decode(item.n)}</h3><span className="dots"/><span className="price">${item.p}</span></div><p>{decode(item.d)} {item.m.includes('vg')?'○':item.m.includes('v')?'●':''} {item.m.includes('n')?'▢':''}</p></div>)}</>}
export function HomePage(){const [slide,setSlide]=useState(0);const [paused,setPaused]=useState(false); const slides=[{image:coffee,label:'Rooted in craftsmanship',line:<>Elevating<br/><em>everyday moments.</em></>,text:'Café & Bakehaus. Rooted in craftsmanship, guided by simplicity.',cta:'Discover SEVN',to:'/story' as const},{image:bakery,label:'Golden layers in rhythm',line:<>Warm from<br/><em>the oven.</em></>,text:'The ovens are on before the lights are. Everything that reaches the counter was made a few metres behind it.',cta:'Explore the menu',to:'/menu' as const},{image:room,label:'A quiet morning ritual',line:<>Come for the coffee.<br/><em>Stay for the hour after it.</em></>,text:'We saved you the corner table.',cta:'Visit SEVN',to:'/visit' as const}];
 const {panelRef,changeSlide}=useHeroPanels(setSlide);
 useEffect(()=>{if(paused||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=window.setInterval(()=>changeSlide((slide+1)%3),6500);return()=>clearInterval(timer)},[paused,slide,changeSlide]);
 const [date,setDate]=useState('');const [guests,setGuests]=useState('2');const [time,setTime]=useState('09:30');const current=slides[slide];if(!current)return null;
 return <div className="home-scroll-scene"><section className="hero" aria-label="SEVN moments" aria-roledescription="carousel" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocusCapture={()=>setPaused(true)} onBlurCapture={()=>setPaused(false)}>{slides.map((s,i)=><img className={`hero-image ${i===slide?'active':''}`} key={s.image} src={s.image} alt={i===slide?['A handcrafted cappuccino at the café bar','Fresh butter croissants from the bakehaus','A quiet, sunlit café room'][i]:''} width="1920" height="1024"/>)}<div className="hero-reveal-panels" ref={panelRef} aria-hidden="true">{[0,1,2,3,4].map(i=><div className="hero-reveal-panel" key={i}/>)}</div><div className="hero-content" key={slide}><div className="hero-emblem"><Coffee/><span>THE SEVEN NOTES</span></div><span className="eyebrow reveal">{current.label}</span><h1 className="reveal">{current.line}</h1><p className="reveal">{current.text}</p><Button variant="hero" asChild><Link to={current.to}>{current.cta} <ArrowRight/></Link></Button></div><Button variant="tool" className="hero-arrow prev" aria-label="Previous slide" onClick={()=>changeSlide((slide+2)%3)}><ChevronLeft/></Button><Button variant="tool" className="hero-arrow next" aria-label="Next slide" onClick={()=>changeSlide((slide+1)%3)}><ChevronRight/></Button><div className="hero-bottom"><span className="location">Bandra West, Mumbai</span><div className="slide-dots">{slides.map((_,i)=><Button variant="dot" key={i} aria-label={`Show slide ${i+1}`} aria-pressed={i===slide} onClick={()=>{if(i!==slide)changeSlide(i)}}/>)}</div><span className="scroll-note">Good things take time <ArrowDown/></span></div><div className="hero-edge"/></section>
 <section className="booking-strip"><div className="container"><div className="booking-copy"><CalendarDays/><div><h2>A table awaits.</h2><p>A little time, just for you.</p></div></div><div className="booking-fields"><select aria-label="Number of guests" value={guests} onChange={e=>setGuests(e.target.value)}>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>{n} {n===1?'guest':'guests'}</option>)}</select><input aria-label="Reservation date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><select aria-label="Reservation time" value={time} onChange={e=>setTime(e.target.value)}>{data.booking.times.map(t=><option key={t}>{t}</option>)}</select><Button variant="cafe" asChild><Link to="/book" search={{date,time,guests}}>Book a table <ArrowRight/></Link></Button></div></div></section>
 <section className="section"><div className="container"><SectionTitle label="A flowing experience" title="A few things worth slowing down for."/><div className="feature-grid">{[{n:'01',title:'A beautiful place.',text:'By nine the corner tables are taken by the same people they were taken by yesterday.',image:room,to:'/visit' as const,cta:'Find your corner'},{n:'02',title:'Feel the coffee.',text:'Seven notes run through the food, the coffee and the room. They started in the kitchen.',image:coffee,to:'/story' as const,cta:'Our story'},{n:'03',title:'Golden layers.',text:'The ovens are on before the lights are. Everything that reaches the counter was made a few metres behind it.',image:bakery,to:'/menu' as const,cta:'See the menu'}].map(x=><article className="feature" key={x.n}><Link className="image-link" to={x.to}><img src={x.image} alt={x.title} width="1600" height="1024" loading="lazy"/></Link><h3><span>{x.n}</span>{x.title}</h3><p>{x.text}</p><Link to={x.to} className="text-link">{x.cta}<ArrowRight/></Link></article>)}</div></div></section>
 <section className="cover"><img src={bakery} alt="Golden croissants, fresh from the oven" loading="lazy" width="1600" height="1024"/><div className="cover-content"><p className="eyebrow">The bakehaus, before the world wakes</p><h2>Rooted in craftsmanship.<br/>Guided by simplicity.</h2><p>Seven notes hold it together. You will find them on the napkins, and you will taste them before you read them.</p><Button variant="hero" asChild><Link to="/story">Read our story <ArrowRight/></Link></Button></div></section>
 <section className="section"><div className="container"><SectionTitle label="What are you here for?" title="Your everyday favourites."/><div className="menu-grid"><MenuRows items={[...(data.menu[0]?.items??[]),...(data.menu[1]?.items.slice(0,3)??[])]}/></div><div className="center-action"><Button variant="cafe" asChild><Link to="/menu">View the full menu <ArrowRight/></Link></Button></div></div></section>
 <section className="notes-band"><div className="container notes-grid">{data.notes.map((note,i)=><Link to="/story" key={note.id}><div className="note-circle">{i===0?<Sun size={24} strokeWidth={1}/>:['','✳','≈','≋','◌','≡','✧'][i]}</div><p>{decode(note.word)}</p></Link>)}</div></section>
 <section className="section"><div className="container"><SectionTitle label="Notes from the bakehaus" title="From the journal."/><div className="feature-grid">{data.journal.entries.slice(0,3).map((entry,i)=><article className="feature" key={entry.t}><Link to="/journal/$slug" params={{slug:String(i+1)}} className="image-link"><img src={[room,coffee,bakery][i]} alt={entry.t} width="1600" height="1024" loading="lazy"/></Link><div className="journal-meta">{entry.c} · {entry.d} · {entry.r} read</div><h3 className="journal-title">{entry.t}</h3><Link className="text-link mt-5" to="/journal/$slug" params={{slug:String(i+1)}}>Read the story<ArrowRight/></Link></article>)}</div></div></section>
 <section className="cover"><img src={room} alt="A quiet corner in the café" width="1600" height="1024" loading="lazy"/><div className="cover-content"><p className="eyebrow">There is always a reason to return</p><h2>Come for the coffee.<br/>Stay for the hour after it.</h2><Button variant="hero" asChild><Link to="/visit">Find us <ArrowRight/></Link></Button></div></section></div>
}
